version: '3'
services:

  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

  java-application:
    ports:
      - "8080:8080"
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      POSTGRES_URL: ${POSTGRES_URL}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://java-application:8080/actuator/health" ]
      interval: 5s
      timeout: 5s
      retries: 20
    depends_on:
      - postgres

  front:
    ports:
      - "3000:3000"
    build:
      context: ./front
      dockerfile: Dockerfile
    depends_on:
      java-application:
        condition: service_healthy